
spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_DATABASE}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true
    hikari:
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 0
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10000
      password: ${REDIS_PASSWORD}
      client-type: lettuce
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
      url: redis://${REDIS_HOST}
  servlet:
    multipart:
      max-request-size: 6400MB
      max-file-size: 6400MB
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true
logging:
  level:
    com.ldx.redis.service.impl: debug
    org.springframework: warn
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
dd-server-config:
  root-dir: .dd