package shop.itbug.ticket.model.dtk

import kotlinx.serialization.Serializable

@Serializable
data class TljResultModel (
    val list: List<ListElement>? = null,
    val model1: String? = null,
    val model2: String? = null,
    val pageId: Long? = null,
    val totalNum: Long? = null
)

@Serializable
data class ListElement (
    val activityEndTime: String? = null,
    val activityStartTime: String? = null,
    val activityType: Long? = null,
    val actualPrice: Long? = null,
    val brand: Long? = null,
    val brandId: Long? = null,
    val brandName: String? = null,
    val brandWenan: String? = null,
    val cid: Long? = null,
    val commissionRate: Double? = null,
    val commissionType: Long? = null,
    val couponConditions: String? = null,
    val couponEndTime: String? = null,
    val couponId: String? = null,
    val couponLink: String? = null,
    val couponPrice: Long? = null,
    val couponReceiveNum: Long? = null,
    val couponRemainCount: Long? = null,
    val couponStartTime: String? = null,
    val couponTotalNum: Long? = null,
    val createTime: String? = null,
    val dailySales: Long? = null,
    val desc: String? = null,
    val descScore: Double? = null,
    val discounts: Double? = null,
    val dsrPercent: Long? = null,
    val dsrScore: Double? = null,
    val dtitle: String? = null,
    val estimateAmount: Long? = null,
    val estimatePrice: Long? = null,
    val firstOrderAmount: String? = null,
    val freeshipRemoteDistrict: Long? = null,
    val goldSellers: Long? = null,
    val goodsBlackStatus: String? = null,
    val goodsId: String? = null,
    val goodsSign: String? = null,
    val haitao: Long? = null,
    val hotPush: Long? = null,
    val hzQuanOver: Long? = null,
    val id: Long? = null,
    val itemLink: String? = null,
    val mainPic: String? = null,
    val marketingMainPic: String? = null,
    val monthSales: Long? = null,
    val originalPrice: Long? = null,
    val quanMLink: Long? = null,
    val sellerBlackStatus: String? = null,
    val sellerId: String? = null,
    val sentiment: String? = null,
    val servicePercent: Long? = null,
    val serviceScore: Double? = null,
    val shipPercent: Long? = null,
    val shipScore: Double? = null,
    val shopLevel: Long? = null,
    val shopName: String? = null,
    val shopType: Long? = null,
    val specialText: List<String>? = null,
    val subcid: List<Long>? = null,
    val tbcid: Long? = null,
    val tchaoshi: Long? = null,
    val teamName: String? = null,
    val title: String? = null,
    val twoHoursSales: Long? = null,
    val video: String? = null,
    val yunfeixian: Long? = null
)
